### ISSUE TITLE
ReplyTo in transaction mails ändern

### ISSUE THREAD

**Issue by ZengineChris** [MeinGrundeinkommen/meingrundeinkommen#171]
Es kommt immer wieder vor das User auf die Transaction Mails antworten. Die Mails kommen dann bei admin@ an. Die Mails sollen an support@ geleitet werden. Im Absender der Mails steht micha@meinbge.de. Das sollte dann ebenfalls support@ sein.

**Comment by ZengineAlex** [comment]
Mit Transaction Mails meinst du die, die Payments betreffen? @ZengineChris

**Comment by ZengineChris** [comment]
Transaction mails benenne ich alle mails die ein script versendet nach einer Aktion eines Users. In diesem Beispiel meine ich die Schalte deinen Account frei Mails, Password zurücksetzten und so weiter.

**Comment by ZengineAlex** [comment]
Als Absender kommt weiterhin micha@meinbge.de

**Comment by ZengineAlex** [comment]
sollte mit dem letzten deploy gefixt sein
