### ISSUE TITLE
Texte für das Account freischalten vereinheitlichen / optimieren

### ISSUE THREAD

**Issue by ZengineChris** [MeinGrundeinkommen/meingrundeinkommen#172]
Wie im dev-discussion beschrieben, ist der content in der TA-Mail zum freischalten des Accounts allenfalls irreführend. Wie im channel beschrieben soll der Content in den Mails und auf der Website optimiert und vereinheitlicht werden.

**Comment by ZengineAlex** [comment]
Aus dev-discussion: 
"Ich schlage vor den Betreff in "Aktiviere deinen Account“ zu ändern. Der Text vor dem Link sollte in etwa „Klicke (folge) dem Link um deinen Account zu aktivieren:“"
