### ISSUE TITLE
SMTP Mails rejected when sending via sparkpost

### ISSUE THREAD

**Issue by jottr** [MeinGrundeinkommen/meingrundeinkommen#193]
We've been trying to migrate our rails app from Mandrill to Sparkpost. We have the app running on a bare metal server, with a dedicated IP with cloudflare in front. 

Sending transactional email from the app on the bare metal server does not work. 
Sending transactional email from the app instance on heroku does work. 

```bash
# production.log

Sent mail to foo@example.com (1513.4ms)
I, [2016-04-28T20:02:51.022835 #17467]  INFO -- : Completed 500 Internal Server Error in 1559ms
F, [2016-04-28T20:02:51.025247 #17467] FATAL -- : 
Net::SMTPAuthenticationError (435 4.7.8 Error: authentication failed: UGFzc3dvcmQ6
):
  /var/app/mge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/smtp.rb:969:in `check_auth_response'
  /var/app/mge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/smtp.rb:751:in `auth_login'
  /var/app/mge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/smtp.rb:732:in `authenticate'
  /var/app/mge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/smtp.rb:567:in `do_start'
  /var/app/mge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
  mail (2.5.4) lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
  mail (2.5.4) lib/mail/message.rb:2129:in `do_delivery'
  mail (2.5.4) lib/mail/message.rb:232:in `block in deliver'
  actionmailer (4.1.0) lib/action_mailer/base.rb:527:in `block in deliver_mail'

```

The string in `Net::SMTPAuthenticationError (435 4.7.8 Error: authentication failed: UGFzc3dvcmQ6
` is base64 encoded, and points to an incorrect password being sent over the wire:

```
$  echo -n 'UGFzc3dvcmQ6' | base64 -D
Password:
```
We've set up and validated `SPF` and `DKIM` records on cloudflare and sparkpost. 
We are able to send Mail via Sparkpost from our local development machines and from the server without problems using this [script](https://gist.github.com/jottr/3879ccad8e9c23cc0e7b7798c2b3383d).

To validate that the application is working, we've set up a heroku instance with our rails application, which was also able to send transactional mail via sparkpost without any problems. This instance is not behind cloudflare.

Trying to do the same on our bare metal server does not work though. 
I've tried to test to send an email via [telnet](https://gist.github.com/jottr/780fe0487cbb3f1d1723b0fcf72b428e).
Which returns the following status: `550 5.6.0 No Sending Domain found in From header`. 
I'm not sure if this is related to the the issue, or me not communicating correctly with the smtp server.

Our SPF records are validated, and _seem_ to be correct: 

```
mein-grundeinkommen.de descriptive text "v=spf1 +a +mx include:_spf.google.com include:spf.mandrillapp.com ip6:2a01:488:66:1000:5bfa:7161:0:1 include:sparkpostmail.com ~all"
mein-grundeinkommen.de descriptive text "google-site-verification=hwHBe2RFXvga8L3tCC5BAVkVH11lVePT8EqHMazT0LM"
```

[This](https://github.com/bohemeyer/meingrundeinkommen/blob/production/config/environments/production.rb#L16) is how we configured SMTP in our Rails application.

**Comment by deviantbits** [comment]
@jottr Some quick questions:

- Are we stuck with SparkPost? Or can we move to SendGrid without any pain?
- Did we verify that the bare metal server reads the correct configuration from `production.rb`?
- Why don't we set `enable_starttls_auto` to `true` in the `config.action_mailer.smtp_settings`?
- Why did we move away from Heroku? Is it merely a cost issue or more than that?

I don't think that your `telnet` issue is related in any way. The manual connection looks fine.

**Comment by jottr** [comment]
> Are we stuck with SparkPost? Or can we move to SendGrid without any pain?

This was mainly a pricing decision. We _could_ re-evaluate. 

> Did we verify that the bare metal server reads the correct configuration from production.rb?

This must be the reason! We have a chef-script which seems to be overwriting the config. 

> Why don't we set enable_starttls_auto to true in the config.action_mailer.smtp_settings?

We disabled this, to test if this could be the culprit. Which it wasn't.

> Why did we move away from Heroku? Is it merely a cost issue or more than that?

We want to move to heroku ASAP.

**Comment by jottr** [comment]
Why do you suggest sendgrid? Do you see some advantage in using their sevice apart from above issue?

**Comment by deviantbits** [comment]
Thanks for the comments.

If the Chef script can be fixed so that Rails reads the correct production configuration, then there's no reason to switch from SparkPost to SendGrid. As a matter of fact, it wouldn't help in any way. :wink:

Ideally, we'd introduce proper `ENV` variables soon so that we don't have to leak production credentials.
