### ISSUE TITLE
Text of the "Datenschutzerklärung" needs to be updated

### ISSUE THREAD

**Issue by jottr** [MeinGrundeinkommen/meingrundeinkommen#202]
In our [Datenschutzerklärung](https://www.mein-grundeinkommen.de/info/datenschutz) we claim that we use mailjet - which is not the case any more. 
The text needs an update ASAP.

[Additional information: misleading information was found faulty [here](https://pod.geraspora.de/posts/4798440)]

**Comment by jottr** [comment]
@strehlst please give a quick update, if you are willing and able to provide such a text, of if I should relay the task to someone else. thx

**Comment by strehlst** [comment]
@jottr Please provide information about which service we use right now. Sparkpost, Mailchimp? And I can assemble a text (I'll be back at work on Tuesday).

**Comment by jottr** [comment]
Awesome! 
Currently we use sparkpost to send transactional and newsletter emails. 
We might temporarily switch sending of the NL to mailchimp. 
When this is the case, we will need to update the text again. 
Thx for helping out. :)

**Comment by strehlst** [comment]
New text is written. Micha will include and deploy it as soon as possible.
