### ISSUE TITLE
A user cant participate in the contest: age not properly validated?

### ISSUE THREAD

**Issue by ZengineChris** [MeinGrundeinkommen/meingrundeinkommen#37]
xxxx@yahoo.com schreibt dass ihre tochter keinen account einrichten kann, obwohl sie bereits letzte woche 14 geworden ist. ist da vllt was nicht richtig aktualisiert?

**Comment by jottr** [comment]
Check https://github.com/MeinGrundeinkommen/meingrundeinkommen/blob/master/app/assets/javascripts/resources/chances.js.coffee
